mailing:
  repository-mode: jpa

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mailing
    username: mailing
    password: mailing
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      auto-startup: true